
name: Run Playwright Tests in Docker

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest
    env:
      APP_USER_NAME: ${{ secrets.APP_USER_NAME }}
      APP_USER_PASSWORD: ${{ secrets.APP_USER_PASSWORD }}
      BASE_URL: ${{ secrets.BASE_URL }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

 
      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run Playwright tests and generate Allure report
        run: docker run --rm playwright-tests