
name: Run Playwright Tests in Docker

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout do código
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Build da imagem Docker
      - name: Build Docker image
        run: docker build -t playwright-tests .

      # 3. Rodar os testes dentro do container
      - name: Run Playwright tests
        run: docker run --rm playwright-tests
