
name: Run Playwright Tests in Docker

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  playwright-tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

 
      - name: Build Docker image
        run: docker build -t playwright-tests .

      - name: Run Playwright tests
        run: docker run --rm playwright-tests
